language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

services:
    - mysql

matrix:
    allow_failures:
        - php: 7.0
        - php: hhvm

env:
    global:
        - DUNKERQUE_DATABASE_HOST=127.0.0.1
        - DUNKERQUE_DATABASE_PASSWORD=null

before_script:
    - cp var/jwt/private.pem.dist var/jwt/private.pem
    - cp var/jwt/public.pem.dist var/jwt/public.pem
    - composer self-update
    - composer install --no-interaction

script:
    - ./bin/run-tests
