security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chain_provider:
            chain:
                providers: [ in_memory, fos_userbundle ]

        in_memory:
            memory:
                users:
                    # Used to generate a JWT token for anymous visitors
                    "Anon.":
                        password: null
                        roles: ROLE_ANONYMOUS

        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        registry_token:
            pattern: ^/token$
            anonymous: true
            stateless: true
            entry_point: registry_entry_point
            http_basic:
                provider: fos_userbundle

        registry:
            pattern: ^/v2/
            anonymous: true
            stateless: true
            entry_point: registry_entry_point
            http_basic:
                provider: fos_userbundle
            lexik_jwt:
                create_entry_point: false

        main:
            anonymous: true
            logout: true
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            remember_me:
                secret: "%secret%"
                lifetime: 2419200 # 4 weeks in seconds
                path: /

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
