services:
    header_response_listener:
        class: AppBundle\EventListener\HeaderResponseListener
        tags:
            - {name: kernel.event_subscriber}

    layer_manager:
        class: AppBundle\Manager\LayerManager
        arguments: ["@doctrine.orm.entity_manager", "%storage_path%"]

    repository_voter:
        class: AppBundle\Security\Voter\RepositoryVoter
        arguments: ["@doctrine.orm.entity_manager", "@security.access.role_hierarchy_voter", "@logger"]
        tags:
            - {name: security.voter}

    form.type.repository:
        class: AppBundle\Form\RepositoryType
        tags:
            - {name: form.type, alias: "repository"}
