services:
    header_response_listener:
        class: AppBundle\EventListener\HeaderResponseListener
        tags:
            - {name: kernel.event_subscriber}

    layer_manager:
        class: AppBundle\Manager\LayerManager
        arguments: ["@doctrine.orm.entity_manager", "@storage"]

    repository_voter:
        class: AppBundle\Security\Voter\RepositoryVoter
        arguments: ["@doctrine.orm.entity_manager", "@security.access.role_hierarchy_voter", "@logger"]
        tags:
            - {name: security.voter}

    form.type.repository:
        class: AppBundle\Form\Type\RepositoryType
        tags:
            - {name: form.type}

    form.type.webhook:
        class: AppBundle\Form\Type\WebhookType
        tags:
            - {name: form.type}

    delayed_event_listener:
        class: AppBundle\EventListener\DelayedEventListener
        tags:
            - {name: kernel.event_subscriber}

    manifest_pull_listener:
        class: AppBundle\EventListener\ManifestPullListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - {name: kernel.event_subscriber}

    manifest_push_listener:
        class: AppBundle\EventListener\ManifestPushListener
        arguments: ["@doctrine.orm.entity_manager", "@swarrot.publisher", "@serializer"]
        tags:
            - {name: kernel.event_subscriber}

    mq.processor.webhook:
        class: AppBundle\Broker\Processor\WebhookProcessor
        arguments: ["@doctrine.orm.entity_manager"]
